# Generated by Django 3.2.9 on 2021-12-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_tasklist_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['-time']},
        ),
    ]
